spring:
  application:
    name: gateway-service

server:
  port: 9000

jwt:
  secret: ${SECRET:rZpHh0TU/um38Zn9W/Hjq1KpPcGCcmJ/IZXlT/4W6yg=}

product:
  service:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8080}

order:
  service:
    url: ${ORDER_SERVICE_URL:http://localhost:8082}

payment:
  service:
    url: ${PAYMENT_SERVICE_URL:http://localhost:8081}